### ISSUE TITLE
FetchError: request to Google token API failed

### ISSUE THREAD

**Issue by labaland** [ismarslomic/google-assistant-oauth#3]
what am i doing wrong ? :( 

Go to this URL in your browser: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&response_type=code&client_id=ddwa13****422dwad34-4r1ld028*dwdw*****vljbr7ddv805jd*d**dwd**.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A3005%2Foauth2callback

Code is 4/0ARtbsJrHn5CjF*dwd***daad*MwgybO4wB8******LA_sziKadSyp5Zd3K7awdawdaDuvq****dwd***
FetchError: request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo EAI_AGAIN oauth2.googleapis.com
.......................
.......................

**Comment by labaland** [comment]
I added this line to docker-compose ((  network_mode: host )) and now it worked
i get message : 
  Tokens acquired.
  Tokens saved to /usr/src/config/tokens.json.

but no file is made xD :(

**Comment by labaland** [comment]
I made tokens.json myself and added the code after "Code is "

Now i get this message in docker container after i try to make a service_call from HomeAssistant:

[2022-09-17T19:11:24.306Z] [OK] Google Assistant Broadcast started at: http://localhost:8085
[2022-09-17T19:14:56.048Z] Sending message (en-GB): Broadcast Hello world!!
[2022-09-17T19:14:56.063Z] Opening OAuth URL. Return here with your code.

dosent work. Is it possible to change localhost to my server IP ?

Ideas? 

Maybe the token is wrong? Is there any other way to get token ?

**Comment by labaland** [comment]
YAY! got it to work. ignore my messages :D I had to 
chmod 777 on the google-assistant-oauth docker folder :) 
Works perfectly!

**Comment by ismarslomic** [comment]
Glad to hear that you find solution on your issue!
