### ISSUE TITLE
Fatal error in , line 0

### ISSUE THREAD

**Issue by roozbehv** [ismarslomic/google-assistant-oauth#4]
Hi, 

I get this error when I try to run the docker:

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ed0156c

I've put the client_secret.json file in /home/pi/config

**Comment by ismarslomic** [comment]
In order to help you I would appreciate that you put more effort in describing the steps to reproduce the issue, and that you include (correctly formatted) log output.

**Comment by roozbehv** [comment]
Sorry the #'s in the output messed up the formatting.

I've downloaded the client_secret.json file as per the instructions and placed in /home/pi/config.

When I run the following:

`docker run --rm -p 3005:3005 -v /home/pi/config:/usr/src/config ismarslomic/google-assistant-oauth:latest`

I get the following output:

`#`
`# Fatal error in , line 0`
`# unreachable code`
`#`
`#`
`#`
`#FailureMessage Object: 0x7ebf856c`

Please let me know where I get more log info. I appreciate your help.

**Comment by roozbehv** [comment]
Not sure but this issue on another project might be related:

https://github.com/svrooij/sonos2mqtt/issues/152

**Comment by ismarslomic** [comment]
Could you please share the client_secret.json content (mask first part of `client_id` and `client_secret`)? Based on the link you shared to related issue this issue might be related to the Docker Image and docker installation on the host. Could you try running the docker command on another machine, to see if you get the same issue?

**Comment by roozbehv** [comment]
Ok I tried another machine and it worked, thanks.
