### ISSUE TITLE
Not able to access the URL running on pi from my Mac

### ISSUE THREAD

**Issue by winchenbach** [ismarslomic/google-assistant-oauth#6]
I *think* I mostly have this working, but when the container executes and I get a URL, I'm not sure how to follow that. I copy the URL and access  it from Mac, but get a message "can't connect to server" which makes sense because it's trying to go to local host. I don't have a web server on my pi (and accessing via command line) so I tried curl with the URL and that doesn't seem to work or result in a tokens.json file.

**Comment by ismarslomic** [comment]
You have two options:
1. run this docker container on your Mac, then the `localhost` will work
2. run this docker container on your pi, but replace the `localhost` with the actual IP address of your pi
